# circleciのバージョン
version: 2.1
jobs:
  build:
    docker:
      # - image: circleci/openjdk:11-jdk-buster-browsers
      - image: openkbs/jdk11-mvn-py3
    steps:
    # CI環境上のworking_directryにgitリポジトリをコピーする
      - checkout
      # キャッシュがsave_cacheされていればリストア（バックアップを適用）する
      - restore_cache:
          # リストアするキャッシュを指定
          key: maven-v1-{{ checksum "pom.xml" }}
    # コマンドを実行する
      - run:
      # run名
          name: ./mvnw install
          # コマンドの実行
          command: ./mvnw install
      # パッケージなどのファイルのキャッシュ
      - save_cache:
          # ファイルのハッシュ値
          key: maven-v1-{{ checksum "pom.xml" }}
          paths: ~/.m2
      # 一時的にファイルをjob間で共有できるようにする
      - persist_to_workspace:
          root: .
          paths: .
          
  test:
    docker:
    # ToDoここのバージョンとか間違ってないか確認 →済
      - image: openkbs/jdk11-mvn-py3
      - image: circleci/mysql:5.7.29
      
        environment:
        # passwordを記述しなくても大丈夫な設定
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: 'TestTempleTaskManager'
          # MYSQL_USER: 'root'
          MYSQL_ROOT_PASSWORD: ''
    steps:
    #  - persist_to_workspace:
          # root: .
          # paths: .
          # ここに入ってテストを実行する
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: unit test
          command: ./mvnw test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: deploy to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
